security:
    
    providers:
        from_database:
            entity:
                class:  App\Entity\User
                property:   username



    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            #user_checker: App\Security\UserChecker # activation du UserChecker créé précédemment
            http_basic: ~
            


            logout:
                path: /logout
                target: /



            form_login:
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }


    encoders:
        App\Entity\User:
            algorithm:  bcrypt
            cost:   12
