security:
    
    providers:
        from_database:
            entity:
                class:  App\Entity\User
                property:   username



    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern:   ^/



            logout:
                path: /logout
                target: /



            form_login:
                check_path: security_login
                login_path: security_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }


    encoders:
        App\Entity\User:
            algorithm:  bcrypt
            cost:   12
