security:
    
    providers:
        from_database:
            entity:
                class:  App\Entity\User
                property:   username



    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern:   ^/



            logout:
                path: /logout
                target: /



            form_login:
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: dash

    role_hierarchy:
        # un membre avec le ROLE_ADMIN aura également le ROLE_USER
        ROLE_ADMIN: ROLE_USER
        # Le ROLE_SUPER_ADMIN avec le ROLE_ALLOWED_TO_SWITCH qui permet de s'authentifier en se faisant passer pour n'importe quel membre. Particulièrement utile pour débugger son code.
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]



    access_control:
        - { path: ^/admin, roles:[ ROLE_ADMIN, ROLE_USER] }
        #- { path: ^/profile, roles: ROLE_USER }





    encoders:
        App\Entity\User:
            algorithm:  bcrypt
            cost:   12
